[2022-12-14T06:20:01.080+0000] {processor.py:153} INFO - Started process (PID=45) to work on /opt/airflow/dags/lesson4/exercise3.py
[2022-12-14T06:20:01.107+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/lesson4/exercise3.py for tasks to queue
[2022-12-14T06:20:01.111+0000] {logging_mixin.py:137} INFO - [2022-12-14T06:20:01.111+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/lesson4/exercise3.py
[2022-12-14T06:20:01.476+0000] {logging_mixin.py:137} INFO - [2022-12-14T06:20:01.433+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/lesson4/exercise3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/lesson4/exercise3.py", line 13, in <module>
    from airflow.operators.udacity_plugin import HasRowsOperator
ModuleNotFoundError: No module named 'airflow.operators.udacity_plugin'
[2022-12-14T06:20:01.488+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/lesson4/exercise3.py
[2022-12-14T06:20:01.609+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/lesson4/exercise3.py took 0.537 seconds
[2022-12-14T06:20:52.903+0000] {processor.py:153} INFO - Started process (PID=134) to work on /opt/airflow/dags/lesson4/exercise3.py
[2022-12-14T06:20:52.922+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/lesson4/exercise3.py for tasks to queue
[2022-12-14T06:20:52.947+0000] {logging_mixin.py:137} INFO - [2022-12-14T06:20:52.945+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/lesson4/exercise3.py
[2022-12-14T06:20:53.504+0000] {logging_mixin.py:137} INFO - [2022-12-14T06:20:53.499+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/lesson4/exercise3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/lesson4/exercise3.py", line 13, in <module>
    from airflow.operators.udacity_plugin import HasRowsOperator
ModuleNotFoundError: No module named 'airflow.operators.udacity_plugin'
[2022-12-14T06:20:53.507+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/lesson4/exercise3.py
[2022-12-14T06:20:53.614+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/lesson4/exercise3.py took 0.719 seconds
[2022-12-14T06:21:24.290+0000] {processor.py:153} INFO - Started process (PID=210) to work on /opt/airflow/dags/lesson4/exercise3.py
[2022-12-14T06:21:24.295+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/lesson4/exercise3.py for tasks to queue
[2022-12-14T06:21:24.299+0000] {logging_mixin.py:137} INFO - [2022-12-14T06:21:24.299+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/lesson4/exercise3.py
[2022-12-14T06:21:24.419+0000] {logging_mixin.py:137} INFO - [2022-12-14T06:21:24.414+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/lesson4/exercise3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/lesson4/exercise3.py", line 13, in <module>
    from airflow.operators.udacity_plugin import HasRowsOperator
ModuleNotFoundError: No module named 'airflow.operators.udacity_plugin'
[2022-12-14T06:21:24.422+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/lesson4/exercise3.py
[2022-12-14T06:21:24.476+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/lesson4/exercise3.py took 0.192 seconds
[2022-12-14T06:21:55.190+0000] {processor.py:153} INFO - Started process (PID=282) to work on /opt/airflow/dags/lesson4/exercise3.py
[2022-12-14T06:21:55.231+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/lesson4/exercise3.py for tasks to queue
[2022-12-14T06:21:55.239+0000] {logging_mixin.py:137} INFO - [2022-12-14T06:21:55.238+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/lesson4/exercise3.py
[2022-12-14T06:21:56.483+0000] {logging_mixin.py:137} INFO - [2022-12-14T06:21:56.102+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/lesson4/exercise3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/lesson4/exercise3.py", line 13, in <module>
    from airflow.operators.udacity_plugin import HasRowsOperator
ModuleNotFoundError: No module named 'airflow.operators.udacity_plugin'
[2022-12-14T06:21:56.561+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/lesson4/exercise3.py
[2022-12-14T06:21:57.192+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/lesson4/exercise3.py took 2.146 seconds
[2022-12-14T06:22:27.693+0000] {processor.py:153} INFO - Started process (PID=355) to work on /opt/airflow/dags/lesson4/exercise3.py
[2022-12-14T06:22:27.697+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/lesson4/exercise3.py for tasks to queue
[2022-12-14T06:22:27.700+0000] {logging_mixin.py:137} INFO - [2022-12-14T06:22:27.700+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/lesson4/exercise3.py
[2022-12-14T06:22:27.836+0000] {logging_mixin.py:137} INFO - [2022-12-14T06:22:27.831+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/lesson4/exercise3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/lesson4/exercise3.py", line 13, in <module>
    from airflow.operators.udacity_plugin import HasRowsOperator
ModuleNotFoundError: No module named 'airflow.operators.udacity_plugin'
[2022-12-14T06:22:27.837+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/lesson4/exercise3.py
[2022-12-14T06:22:27.916+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/lesson4/exercise3.py took 0.246 seconds
[2022-12-14T06:23:15.019+0000] {processor.py:153} INFO - Started process (PID=406) to work on /opt/airflow/dags/lesson4/exercise3.py
[2022-12-14T06:23:15.063+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/lesson4/exercise3.py for tasks to queue
[2022-12-14T06:23:15.101+0000] {logging_mixin.py:137} INFO - [2022-12-14T06:23:15.101+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/lesson4/exercise3.py
[2022-12-14T06:23:16.174+0000] {logging_mixin.py:137} INFO - [2022-12-14T06:23:16.152+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/lesson4/exercise3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/lesson4/exercise3.py", line 13, in <module>
    from airflow.operators.udacity_plugin import HasRowsOperator
ModuleNotFoundError: No module named 'airflow.operators.udacity_plugin'
[2022-12-14T06:23:16.177+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/lesson4/exercise3.py
[2022-12-14T06:23:16.366+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/lesson4/exercise3.py took 1.412 seconds
[2022-12-14T06:29:12.057+0000] {processor.py:153} INFO - Started process (PID=563) to work on /opt/airflow/dags/lesson4/exercise3.py
[2022-12-14T06:29:12.095+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/lesson4/exercise3.py for tasks to queue
[2022-12-14T06:29:12.132+0000] {logging_mixin.py:137} INFO - [2022-12-14T06:29:12.131+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/lesson4/exercise3.py
[2022-12-14T06:29:22.853+0000] {logging_mixin.py:137} INFO - [2022-12-14T06:29:22.467+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/lesson4/exercise3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/lesson4/exercise3.py", line 13, in <module>
    from airflow.operators.udacity_plugin import HasRowsOperator
ModuleNotFoundError: No module named 'airflow.operators.udacity_plugin'
[2022-12-14T06:29:22.964+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/lesson4/exercise3.py
[2022-12-14T06:29:27.208+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/lesson4/exercise3.py took 15.666 seconds
[2022-12-14T06:42:22.243+0000] {processor.py:153} INFO - Started process (PID=784) to work on /opt/airflow/dags/lesson4/exercise3.py
[2022-12-14T06:42:22.404+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/lesson4/exercise3.py for tasks to queue
[2022-12-14T06:46:08.228+0000] {processor.py:153} INFO - Started process (PID=64) to work on /opt/airflow/dags/lesson4/exercise3.py
[2022-12-14T06:46:08.245+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/lesson4/exercise3.py for tasks to queue
[2022-12-14T06:46:08.292+0000] {logging_mixin.py:137} INFO - [2022-12-14T06:46:08.292+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/lesson4/exercise3.py
[2022-12-14T06:46:09.246+0000] {logging_mixin.py:137} INFO - [2022-12-14T06:46:09.203+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/lesson4/exercise3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/lesson4/exercise3.py", line 13, in <module>
    from airflow.operators.udacity_plugin import HasRowsOperator
ModuleNotFoundError: No module named 'airflow.operators.udacity_plugin'
[2022-12-14T06:46:09.266+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/lesson4/exercise3.py
[2022-12-14T06:46:09.907+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/lesson4/exercise3.py took 1.757 seconds
[2022-12-14T06:51:32.270+0000] {processor.py:153} INFO - Started process (PID=208) to work on /opt/airflow/dags/lesson4/exercise3.py
[2022-12-14T06:51:32.329+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/lesson4/exercise3.py for tasks to queue
[2022-12-14T06:51:32.445+0000] {logging_mixin.py:137} INFO - [2022-12-14T06:51:32.444+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/lesson4/exercise3.py
[2022-12-14T06:51:33.613+0000] {logging_mixin.py:137} INFO - [2022-12-14T06:51:33.606+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/lesson4/exercise3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/lesson4/exercise3.py", line 13, in <module>
    from airflow.operators.udacity_plugin import HasRowsOperator
ModuleNotFoundError: No module named 'airflow.operators.udacity_plugin'
[2022-12-14T06:51:33.624+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/lesson4/exercise3.py
[2022-12-14T06:51:34.113+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/lesson4/exercise3.py took 2.107 seconds
[2022-12-14T07:34:38.704+0000] {processor.py:153} INFO - Started process (PID=57) to work on /opt/airflow/dags/lesson4/exercise3.py
[2022-12-14T07:34:38.727+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/lesson4/exercise3.py for tasks to queue
[2022-12-14T07:34:38.760+0000] {logging_mixin.py:137} INFO - [2022-12-14T07:34:38.741+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/lesson4/exercise3.py
[2022-12-14T07:34:40.634+0000] {logging_mixin.py:137} INFO - [2022-12-14T07:34:40.574+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/lesson4/exercise3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/lesson4/exercise3.py", line 13, in <module>
    from airflow.operators.udacity_plugin import HasRowsOperator
ModuleNotFoundError: No module named 'airflow.operators.udacity_plugin'
[2022-12-14T07:34:40.648+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/lesson4/exercise3.py
[2022-12-14T07:34:40.898+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/lesson4/exercise3.py took 2.341 seconds
